### ISSUE TITLE
Getting this error, every time I try to run this container

### ISSUE THREAD

**Issue by maifeeulasad** [kenchan0130/docker-simplesamlphp#34] opened 2022-07-20 09:39 UTC
```
Error invoking remote method 'docker-start-container': Error: (HTTP code 400) unexpected - failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/23b0b8faec0b18602c62fc5de9731b0018bbf87fac926cc4de8d14357c7c7ecc" to rootfs at "/var/www/simplesamlphp/config/authsources.php": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/23b0b8faec0b18602c62fc5de9731b0018bbf87fac926cc4de8d14357c7c7ecc:/var/www/simplesamlphp/config/authsources.php (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by kenchan0130** [comment] 2022-08-21 15:07
@maifeeulasad 

What command did you run that caused this error?
Also, what is your reproduction environment?

**Comment by maifeeulasad** [comment] 2022-08-22 07:43
I was setting up this repo, but I couldn't: https://github.com/OneUptime/oneuptime

And here is my system info (Windows):
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 AMD Ryzen 3 5300U with Radeon Graphics
    Memory: 2.83 GB / 7.35 GB
  Binaries:
    Node: 16.16.0 - D:\tools\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - D:\tools\nodejs\npm.CMD
  Managers:
    pip3: 22.2.1 - C:\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.33.0. - /cmd/git
    FFmpeg: 10.3.0 - D:\tools\ffmpeg-2021-10-18-git-d04c005021-essentials_build\bin\ffmpeg.EXE
  Virtualization:
    Docker: 20.10.17 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.66.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.32630.194 (Visual Studio Community 2019)
  Languages:
    Java: javac 17 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
    Python: 3.10.6 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.19041.1566
```

And here is the info for Ubuntu (WSL):
```
  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 3 5300U with Radeon Graphics
    Memory: 5.37 GB / 5.68 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /mnt/c/Users/Hp/AppData/Roaming/npm/yarn
    npm: 8.14.0 - /usr/local/bin/npm
  Managers:
    Apt: 2.0.9 - /usr/bin/apt
    pip3: 20.0.2 - /usr/bin/pip3
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Virtualization:
    Docker: 20.10.17 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.66.2 - /mnt/c/Program Files/Microsoft VS Code/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.8.10 - /usr/bin/python3

```

**Comment by kenchan0130** [comment] 2022-12-29 14:47
In your case, it seems that the VOLUME mount is probably failing.
What command did you run?

**Comment by kenchan0130** [comment] 2023-08-23 07:27
Since the time has passed, I will be close this issue.
If the problem has not been resolved, please feel free to reopen.

**Closed by kenchan0130** 2023-08-23 07:27 UTC
